server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-a
              uri: lb://SERVICE-A
              predicates:
                - Path=/service-a/**

            - id: service-b
              uri: lb://SERVICE-B
              predicates:
                - Path=/service-b/**